# This is a basic workflow to help you get started with Actions
name: build

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the eleven branch
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # 为了避免莫名其妙的问题，禁用深度克隆，拉取完整代码
          fetch-depth: 0

      # 新增步骤：拉取子模块【Kernelsu  Anykernel】
      - name: Update Submodules
        run: git submodule update --init --recursive  --remote

      # 下载指定版本的 clang 17.0.2 和 GCC 4.9
      - name: Download clang
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git aarch64
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git arm 
          tar -xvf clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
          
      # 下载Nethunter内核和设备包
      - name: Download Nethunter
        run: |
          git clone git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-project.git
          git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernel.git
          
      - name: Build
        run: |
          bash ./build.sh

      - name: Nethunter_Build
        run: |
          cp mi9_nethunter_buildconfig kali-nethunter-kernel/config
          bash ./kali-nethunter-kernel/build.sh

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            kernel_out/*.zip
